# Generated by Django 5.0.7 on 2024-07-18 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='profiles/')),
                ('place', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=100)),
                ('panchayath', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('principal', models.CharField(max_length=100)),
                ('principal_contact_number', models.CharField(max_length=15)),
                ('principal_image', models.ImageField(upload_to='principals/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='profiles/')),
                ('phone', models.CharField(max_length=15)),
                ('parent_name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('adhere_number', models.CharField(max_length=15, unique=True)),
                ('parent_phone_number', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('panchayath', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('batch', models.PositiveIntegerField()),
                ('current_class', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('studying', 'Studying'), ('stopped', 'Stopped'), ('removed', 'Removed')], default='studying', max_length=10)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.college')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='profiles/')),
                ('phone', models.CharField(max_length=15)),
                ('degree', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('exam_invigilator', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('classes', models.ManyToManyField(related_name='teachers', to='account.class')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.college')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
