# Generated by Django 5.0.7 on 2024-07-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_teacher_classes_college_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='college',
            name='principal_contact_number',
        ),
        migrations.RemoveField(
            model_name='college',
            name='principal_image',
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
    ]
