# Generated by Django 5.0.7 on 2024-08-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_college_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='profile',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
