# Generated by Django 5.0.7 on 2024-08-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_college_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='profile',
            field=models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='profiles/'),
        ),
    ]
